version: '3.8'

services: 
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    environment: 
      - SECRET_KEY=085%-&b_w-rae80o_r*ptldp0+2oeu^$$#5pr!ke^cpcl0lj&=b
      - DEBUG=1
    volumes: 
      - .:/code
    ports: 
      - 8000:8000
    depends_on: 
      - db
  db:
    image: postgres:13
    environment: 
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - "5432:5432"
    volumes: 
      - postgres_data:/var/lib/postgresql/data/

volumes: 
  postgres_data: